### ISSUE TITLE
As a part of issue #3,  Implement the ability to activate a spectator mode "automatic slow rotation of the camera". Then implement the ability to de-activate said spectator mode "normal camera rotation functionality".

### ISSUE THREAD

**Issue by XJamesWrightX** [Team-10-But-Better/Craft#10]
Task Description: Implement the ability to activate a spectator mode "automatic slow rotation of the camera". Then implement the ability to de-activate said spectator mode "normal camera rotation functionality".

**Comment by harroopsingh1993** [comment]
The ability to activate a spectator mode "automatic slow rotation of the camera" is implemented.
