### ISSUE TITLE
As a part of issue #3,  Implement the ability to press a certain key to allow the player to automatically walk forward. Then implement the ability to press another key or the same key, to disable "automatically walking forward.

### ISSUE THREAD

**Issue by XJamesWrightX** [Team-10-But-Better/Craft#8]
Task Description: Implement the ability to press a certain key to allow the player to automatically walk forward. Then implement the ability to press another key or the same key, to disable "automatically walking forward.

**Comment by DragonTamer9001** [comment]
Completed as Branch Issue #3 merge
